In [3]:
import pandas as pd
import numpy as np

# Creating our pizza shop data
data = {
    'date':     ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    'pizza':    ['Margherita', 'Pepperoni', 'Margherita', 'BBQ Chicken', 'Pepperoni', 'BBQ Chicken', 'Margherita'],
    'price':    [12, 15, 12, 18, 15, 18, 12],
    'quantity': [10, 8,  6,  12, 15, 20, 18],
    'area':     ['Downtown', 'Suburbs', 'Downtown', 'Suburbs', 'Downtown', 'Suburbs', 'Downtown']
}

df = pd.DataFrame(data)
print(df)
# How many rows and columns?
print(df.shape)

  date        pizza  price  quantity      area
0  Mon   Margherita     12        10  Downtown
1  Tue    Pepperoni     15         8   Suburbs
2  Wed   Margherita     12         6  Downtown
3  Thu  BBQ Chicken     18        12   Suburbs
4  Fri    Pepperoni     15        15  Downtown
5  Sat  BBQ Chicken     18        20   Suburbs
6  Sun   Margherita     12        18  Downtown
(7, 5)

In [ ]:
# Peek at first 5 rows
df.head()

  date        pizza  price  quantity      area
0  Mon   Margherita     12        10  Downtown
1  Tue    Pepperoni     15         8   Suburbs
2  Wed   Margherita     12         6  Downtown
3  Thu  BBQ Chicken     18        12   Suburbs
4  Fri    Pepperoni     15        15  Downtown

In [ ]:
# Peek at last 5 rows
df.tail()

  date        pizza  price  quantity      area
2  Wed   Margherita     12         6  Downtown
3  Thu  BBQ Chicken     18        12   Suburbs
4  Fri    Pepperoni     15        15  Downtown
5  Sat  BBQ Chicken     18        20   Suburbs
6  Sun   Margherita     12        18  Downtown

In [ ]:
df.tail(3)

  date        pizza  price  quantity      area
4  Fri    Pepperoni     15        15  Downtown
5  Sat  BBQ Chicken     18        20   Suburbs
6  Sun   Margherita     12        18  Downtown

In [ ]:
# What data types are in each column?
df.dtypes

date          str
pizza         str
price       int64
quantity    int64
area          str
dtype: object

In [ ]:
# Full summary of your dataset in one shot
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      7 non-null      str
 1   pizza     7 non-null      str
 2   price     7 non-null      int64
 3   quantity  7 non-null      int64
 4   area      7 non-null      str
dtypes: int64(2), str(3)
memory usage: 412.0 bytes

Lesson 2 — Selecting columns and rows

In [ ]:
# Get just the pizza column
print(df['pizza'])

0     Margherita
1      Pepperoni
2     Margherita
3    BBQ Chicken
4      Pepperoni
5    BBQ Chicken
6     Margherita
Name: pizza, dtype: str

In [ ]:
# One column — uses single brackets
print(type(df['pizza']))

# The full dataframe
print(type(df))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [4]:
print(df['pizza'])
# Multiple columns — double brackets
print(df[['pizza', 'price', 'quantity']])

0     Margherita
1      Pepperoni
2     Margherita
3    BBQ Chicken
4      Pepperoni
5    BBQ Chicken
6     Margherita
Name: pizza, dtype: str
         pizza  price  quantity
0   Margherita     12        10
1    Pepperoni     15         8
2   Margherita     12         6
3  BBQ Chicken     18        12
4    Pepperoni     15        15
5  BBQ Chicken     18        20
6   Margherita     12        18

In [5]:
# This is exactly the same thing
columns_i_want = ['pizza', 'price', 'quantity']
print(df[columns_i_want])

         pizza  price  quantity
0   Margherita     12        10
1    Pepperoni     15         8
2   Margherita     12         6
3  BBQ Chicken     18        12
4    Pepperoni     15        15
5  BBQ Chicken     18        20
6   Margherita     12        18

In [6]:
print(df[['pizza']])

         pizza
0   Margherita
1    Pepperoni
2   Margherita
3  BBQ Chicken
4    Pepperoni
5  BBQ Chicken
6   Margherita

In [9]:
print(df['price'].mean())   # ✅ average of one column
print(df[['price']].mean())  # ✅ also works but returns a DataFrame
#df['pizza'].mean()    # ❌ crashes — can't average text

14.571428571428571
price    14.571429
dtype: float64

In [10]:
# Using the result in a calculation — Series way is cleaner
avg = df['price'].mean()
print("Prices above average:", df[df['price'] > avg]['price'])

Prices above average: 1    15
3    18
4    15
5    18
Name: price, dtype: int64

In [11]:
print(df[df["pizza"] == 'BBQ Chicken'])

  date        pizza  price  quantity     area
3  Thu  BBQ Chicken     18        12  Suburbs
5  Sat  BBQ Chicken     18        20  Suburbs

In [12]:
# Plain Python way — filtering Pepperoni orders
pepperoni_orders = []
for i in range(len(data['pizza'])):
    if data['pizza'][i] == 'Pepperoni':
        pepperoni_orders.append({
            'date': data['date'][i],
            'pizza': data['pizza'][i],
            'price': data['price'][i],
            'quantity': data['quantity'][i],
            'area': data['area'][i]
        })

for order in pepperoni_orders:
    print(order)

{'date': 'Tue', 'pizza': 'Pepperoni', 'price': 15, 'quantity': 8, 'area': 'Suburbs'}
{'date': 'Fri', 'pizza': 'Pepperoni', 'price': 15, 'quantity': 15, 'area': 'Downtown'}

In [13]:
# Orders from Downtown only
print(df[df['area'] == 'Downtown'])

  date       pizza  price  quantity      area
0  Mon  Margherita     12        10  Downtown
2  Wed  Margherita     12         6  Downtown
4  Fri   Pepperoni     15        15  Downtown
6  Sun  Margherita     12        18  Downtown

In [14]:
# Orders where quantity is more than 10
print(df[df['quantity'] > 10])

  date        pizza  price  quantity      area
3  Thu  BBQ Chicken     18        12   Suburbs
4  Fri    Pepperoni     15        15  Downtown
5  Sat  BBQ Chicken     18        20   Suburbs
6  Sun   Margherita     12        18  Downtown

In [15]:
# Orders where price is 18 AND area is Suburbs
print(df[(df['price'] == 18) & (df['area'] == 'Suburbs')])

  date        pizza  price  quantity     area
3  Thu  BBQ Chicken     18        12  Suburbs
5  Sat  BBQ Chicken     18        20  Suburbs

In [16]:
df['pizza'] == 'Pepperoni'

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: pizza, dtype: bool

In [24]:
# Step 1 — see the True/False list
mask = df['pizza'] == 'Pepperoni'
print(mask)
print("---")

# Step 2 — use it to filter
print(df[mask])
print(df[~mask])

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: pizza, dtype: bool
---
  date      pizza  price  quantity      area
1  Tue  Pepperoni     15         8   Suburbs
4  Fri  Pepperoni     15        15  Downtown
  date        pizza  price  quantity      area
0  Mon   Margherita     12        10  Downtown
2  Wed   Margherita     12         6  Downtown
3  Thu  BBQ Chicken     18        12   Suburbs
5  Sat  BBQ Chicken     18        20   Suburbs
6  Sun   Margherita     12        18  Downtown

In [25]:
# Pepperoni orders from Downtown only
print(df[(df['pizza'] == 'Pepperoni') & (df['area'] == 'Downtown')])

  date      pizza  price  quantity      area
4  Fri  Pepperoni     15        15  Downtown

In [28]:
# Challenge 1 — Show orders where quantity is more than 10 AND price is 12
print(df[(df['quantity'] > 10 ) & (df['price'] == 12)])

# Challenge 2 — Show orders that are either Margherita OR BBQ Chicken
print(df[(df['pizza'] == 'Margherita') | (df['pizza'] == 'BBQ Chicken')])

# Challenge 3 — Show all orders that are NOT from Suburbs
print(df[(df['area'] != 'Suburbs')])

  date       pizza  price  quantity      area
6  Sun  Margherita     12        18  Downtown
  date        pizza  price  quantity      area
0  Mon   Margherita     12        10  Downtown
2  Wed   Margherita     12         6  Downtown
3  Thu  BBQ Chicken     18        12   Suburbs
5  Sat  BBQ Chicken     18        20   Suburbs
6  Sun   Margherita     12        18  Downtown
  date       pizza  price  quantity      area
0  Mon  Margherita     12        10  Downtown
2  Wed  Margherita     12         6  Downtown
4  Fri   Pepperoni     15        15  Downtown
6  Sun  Margherita     12        18  Downtown

"Which pizza type made the most money last week?"

In [29]:
#First — plain Python way so you feel the pain:

# Plain Python — total quantity per pizza type
pizzas = ['Margherita', 'Pepperoni', 'BBQ Chicken']

for pizza in pizzas:
    total = 0
    for i in range(len(data['pizza'])):
        if data['pizza'][i] == pizza:
            total += data['quantity'][i]
    print(pizza, ":", total)

Margherita : 34
Pepperoni : 23
BBQ Chicken : 32

In [31]:
print(df.groupby("pizza")["quantity"].sum())

pizza
BBQ Chicken    32
Margherita     34
Pepperoni      23
Name: quantity, dtype: int64

In [34]:
print("Total Quantity :: ",df.groupby('pizza')['quantity'].sum())
print("\naverage quantity ::" ,df.groupby('pizza')['quantity'].mean()) 
print("\nhighest price :: ",df.groupby('pizza')['price'].max())     
print("\nhow many orders ::",df.groupby('pizza')['quantity'].count())

Total Quantity ::  pizza
BBQ Chicken    32
Margherita     34
Pepperoni      23
Name: quantity, dtype: int64

average quantity :: pizza
BBQ Chicken    16.000000
Margherita     11.333333
Pepperoni      11.500000
Name: quantity, dtype: float64

highest price ::  pizza
BBQ Chicken    18
Margherita     12
Pepperoni      15
Name: price, dtype: int64

how many orders :: pizza
BBQ Chicken    2
Margherita     3
Pepperoni      2
Name: quantity, dtype: int64

In [35]:
# Which area — Downtown or Suburbs — generates more total revenue?

df['revenue'] = df['price'] * df['quantity']
print(df)

  date        pizza  price  quantity      area  revenue
0  Mon   Margherita     12        10  Downtown      120
1  Tue    Pepperoni     15         8   Suburbs      120
2  Wed   Margherita     12         6  Downtown       72
3  Thu  BBQ Chicken     18        12   Suburbs      216
4  Fri    Pepperoni     15        15  Downtown      225
5  Sat  BBQ Chicken     18        20   Suburbs      360
6  Sun   Margherita     12        18  Downtown      216

In [37]:
# Which area generates more total revenue?
print("\nGenerates more total revenue ::" ,df.groupby('area')['revenue'].sum())

Generates more total revenue :: area
Downtown    633
Suburbs     696
Name: revenue, dtype: int64

In [39]:
# What is the total revenue AND average quantity per pizza type?
print(df.groupby('pizza').agg({
    'revenue': 'sum',
    'quantity': 'mean'
}))

             revenue   quantity
pizza
BBQ Chicken      576  16.000000
Margherita       408  11.333333
Pepperoni        345  11.500000

In [42]:
df.groupby('pizza').agg({
    'revenue': 'sum',
    'quantity': 'mean',
    'price': 'max',
    'date': 'count'
})

             revenue   quantity  price  date
pizza
BBQ Chicken      576  16.000000     18     2
Margherita       408  11.333333     12     3
Pepperoni        345  11.500000     15     2

In [45]:
# Which day of the week had the highest total revenue?

df.groupby('date')["revenue"].sum()

date
Fri    225
Mon    120
Sat    360
Sun    216
Thu    216
Tue    120
Wed     72
Name: revenue, dtype: int64

In [46]:
print(df.groupby('date')['revenue'].sum().sort_values(ascending=False))

date
Sat    360
Fri    225
Sun    216
Thu    216
Mon    120
Tue    120
Wed     72
Name: revenue, dtype: int64

In [48]:
df.groupby('date')['revenue'].sum().sort_values(ascending=True)          # sort highest to lowest

date
Wed     72
Mon    120
Tue    120
Sun    216
Thu    216
Fri    225
Sat    360
Name: revenue, dtype: int64

In [51]:
# Read the csv 
df = pd.read_csv('pizza_orders.csv')
print(df)

   date        pizza  price  quantity      area
0   Mon   Margherita     12        10  Downtown
1   Tue    Pepperoni     15         8   Suburbs
2   Wed   Margherita     12         6  Downtown
3   Thu  BBQ Chicken     18        12   Suburbs
4   Fri    Pepperoni     15        15  Downtown
5   Sat  BBQ Chicken     18        20   Suburbs
6   Sun   Margherita     12        18  Downtown
7   Mon    Pepperoni     15         9  Downtown
8   Tue  BBQ Chicken     18        14   Suburbs
9   Wed   Margherita     12         7  Downtown
10  Thu    Pepperoni     15        11   Suburbs
11  Fri  BBQ Chicken     18        16  Downtown

In [53]:
print(df.shape,"\n")
print(df.head(),"\n")
print(df.tail(),"\n")
print(df.dtypes,"\n")
df.info()

(12, 5)

  date        pizza  price  quantity      area
0  Mon   Margherita     12        10  Downtown
1  Tue    Pepperoni     15         8   Suburbs
2  Wed   Margherita     12         6  Downtown
3  Thu  BBQ Chicken     18        12   Suburbs
4  Fri    Pepperoni     15        15  Downtown

   date        pizza  price  quantity      area
7   Mon    Pepperoni     15         9  Downtown
8   Tue  BBQ Chicken     18        14   Suburbs
9   Wed   Margherita     12         7  Downtown
10  Thu    Pepperoni     15        11   Suburbs
11  Fri  BBQ Chicken     18        16  Downtown

date          str
pizza         str
price       int64
quantity    int64
area          str
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      12 non-null     str
 1   pizza     12 non-null     str
 2   price     12 non-null     int64
 3   quantity  12 non-null     int64
 4   area      12 non-null     str
dtypes: int64(2), str(3)
memory usage: 612.0 bytes

In [54]:
# Step 3 — clean and analyze
df['revenue'] = df['price'] * df['quantity']
df.groupby('pizza')['revenue'].sum()

pizza
BBQ Chicken    1116
Margherita      492
Pepperoni       645
Name: revenue, dtype: int64

In [65]:
# Question 1 — Which pizza type has highest total revenue?
df['revenue'] = df['price'] * df['quantity']
print(df.groupby('pizza')['revenue'].sum().sort_values(ascending=False))    

# Question 2 — Which area orders more on average (quantity)?
print("\n",df.groupby('area')['quantity'].mean().sort_values(ascending=True))   

# Question 3 — What is the total revenue per day sorted highest to lowest?
print("\n",df.groupby('date')['revenue'].sum().sort_values(ascending=False))

pizza
BBQ Chicken    1116
Pepperoni       645
Margherita      492
Name: revenue, dtype: int64

 area
Downtown    11.571429
Suburbs     13.000000
Name: quantity, dtype: float64

 date
Fri    513
Thu    381
Tue    372
Sat    360
Mon    255
Sun    216
Wed    156
Name: revenue, dtype: int64